///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesLogo = 'assets/images/logo.jpeg';
  static const String rawAdi = 'assets/raw/adi.json';
  static const String rawMotorcycle = 'assets/raw/motorcycle.json';


}
